name: Test Staging Workflow

on:
  push:
    branches:
      - test-workflow-branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo '-----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAgEAxeQAdzuW66F7LVtt8Hq45Y7bBhbeWu/DVXNRWPdMA+5cbmaU4NHQ
        oDY4hMPCni5R6pzCV8KhJq5KVlp6QixVA84+L/5ptUNoXrsX9FKjbSXrfOmefP06/w0Xx4
        8OghAwbKsa1tLeGj19GpBiZZgMHDGoigEPKf2TAEGnlDbZvHZ2mfo8reiazah+IpfmIK2W
        jvh1pr+Jw5spvnRhfHUPGa5sxj69fJWJH6Y3Np0NtCA/CMiKQ/OEWbeeQxGL0c6gCTaIT6
        v6UYGBH7OqbbR53bXoKgs2ptJyFmZfsFUaOVa21D2DNgcWAvFNssCaxL+r6GXB6sjF8ydb
        5iT4+EGPG3h4AnSdduxM9iCvigH5gtFcNlDs2MEnSiPYISEGhiY+CC4sr8e/Zw4XRO1uFS
        tTm830td7n5Q6ISBdNp2dVMXwcQrEPQX+tFCRjUjMIWRqAdtNkeQ7MZucSZ/pXdV5DVIQb
        VfXa/0b94INn73sIOLMDBtNhT8vkxZMktVWsVkapDefPAz6uKuHyxR4u3xvKTKuvh2lkS7
        10Zy2UW4rGAA8zeLmRMN3WVN31G2K3ItkHVX3X0vEX4d7SYRMWtCmVqp4qIE2tp2f04eyF
        2wFXRsEAvfAYLRdNSQwCoVH4oYUzhd6S7YtYYBH9w+LEmiPiw8UYdhC77amBVFrKdjm6du
        MAAAdYJ3DBDCdwwQwAAAAHc3NoLXJzYQAAAgEAxeQAdzuW66F7LVtt8Hq45Y7bBhbeWu/D
        VXNRWPdMA+5cbmaU4NHQoDY4hMPCni5R6pzCV8KhJq5KVlp6QixVA84+L/5ptUNoXrsX9F
        KjbSXrfOmefP06/w0Xx48OghAwbKsa1tLeGj19GpBiZZgMHDGoigEPKf2TAEGnlDbZvHZ2
        mfo8reiazah+IpfmIK2Wjvh1pr+Jw5spvnRhfHUPGa5sxj69fJWJH6Y3Np0NtCA/CMiKQ/
        OEWbeeQxGL0c6gCTaIT6v6UYGBH7OqbbR53bXoKgs2ptJyFmZfsFUaOVa21D2DNgcWAvFN
        ssCaxL+r6GXB6sjF8ydb5iT4+EGPG3h4AnSdduxM9iCvigH5gtFcNlDs2MEnSiPYISEGhi
        Y+CC4sr8e/Zw4XRO1uFStTm830td7n5Q6ISBdNp2dVMXwcQrEPQX+tFCRjUjMIWRqAdtNk
        eQ7MZucSZ/pXdV5DVIQbVfXa/0b94INn73sIOLMDBtNhT8vkxZMktVWsVkapDefPAz6uKu
        HyxR4u3xvKTKuvh2lkS710Zy2UW4rGAA8zeLmRMN3WVN31G2K3ItkHVX3X0vEX4d7SYRMW
        tCmVqp4qIE2tp2f04eyF2wFXRsEAvfAYLRdNSQwCoVH4oYUzhd6S7YtYYBH9w+LEmiPiw8
        UYdhC77amBVFrKdjm6duMAAAADAQABAAACAE3bxBclWd7BfQ4+b8Xy8vZWu3Ps4XVT6j2f
        jnz7Z2wQh0tkjuTZiETQsHID93l27gHpxUj0KaVnY5YQKRQKDzTdG3iUl5CaweCrqeQV83
        jJN5rA6/tvQpwA0b9RWLrxlavbskadVodqc+NUtXIVXYZmP1J00juKKiEqs71Ly2UsEsPI
        QcGGyAlsZpxDuWZYBemgdeGycIiGbukhLw3hnJxVFTT2kGUJDJdoNUcGidK58TMKe+P6Vr
        NZ3Cm1KJbWvf6B9yWpm2YgFuabMM3S+TOzE3IfUVRXbk3D35goE5ZFuM9OmGZUaWOk/xX6
        U6pfY0qfZqlybveZH74wA8jhOmU5g+WxFKXonBBDVdUm4oS768DBheg1lBDF0VIZ1ERmyh
        2tDMuFFRyLjQOZhXAmufmVdn/snOw0EJytfW7tw4jQqk5hZpaFaIOTQIEGrGfj9SrL+fin
        5uTo3Uqeb4em0oQ3pm5KEamWHVT1q1AsEubbgs1zgCHXrI6ZUU+bxNpuqFqAXbzmc+yu9t
        JF3hwaF6kMYWXNvUo95orrTdCwer3N6cr/yGGj8xlcdeQPbVPOox70OZNOZddLsv2cEOIy
        cwJ0FZ0N2xZ74p0Z+lBTewaAvkfDxEmOmLjJOac57wq4DSC9txB6rHYG4GYHHjB/uVrNLL
        YgwzCohSYCSyQUGjqJAAABACKY14ANTqy/54gHI2cFmVA87lBj2yV7a+Hf9ybCv/4CYgq+
        +HclTDiv3CwYMEPwbEmV3DnS9fnXusB3U3681favPVrxPa9rBsRzPUcyjuUJDXeTjaSeUq
        fcBUIoAAuI6yKDY0lwFHa/de6lMj6FMBCdELwEPWmwTrenggRRvU8udcPVNT017KQTvXib
        DmCvDtaV9JpMnkTry2ijtOkQxrFQay6dSa9PrAgxpubvDHE6odbpOOoKF2rMAwVJ1BVJM/
        RENnb4/Pch1bJrpY7JmxuqiN5+CiMD9CEh5g2HRdRLpkPUg4crxUy8SRXsU3BMA0ypHnYw
        TVhdsEtG3dw8cYkAAAEBAPjAryvpudPIghLZdXUtfKYIgLamoBhzY32bDr5ITRYlhOe1+J
        pmwJqxrgoxtnum6f0Mx1B12EeRG5rbLVTYRuOyyRilbRn+2TVAJQxrmZ2fMW6zSOc+MpHn
        NVsee6TB09K9buMC8WAp9yDALkkKZw5HCzGJWxoKHwuaEgkkbLgFukwfx7igOsX6ZaOpfq
        s7+6ZQWc8sUaOkta7yZs62AZR/U+ak1/Iz8Vvmwv/p3CZD0vdGZHwfyOwNh71RxVdDGMIV
        tBuouA9sz3Y2yGD1uMzpRV6r6jdvDGyvu2q6coLfR8BGI6/Ho+kUrIEWLrOxMmBVnEVYsi
        3pPAYCVRDnPn8AAAEBAMun9tooVg7MRAHcoMoT0a8juraDezaTIl501Gby8Ivdu6BZdhQs
        AazGziw6W5EvBQpM5fowPMK1SFLtFiwUEXt62VYfbZmf9qZh4/ApVh2bnewQ8JhYS77zyI
        qSAFLL4oEb64lO8Em0PWNoObDN5+YGn7kt2geFYks36A+tEmCIh1ZNsdi/pHJ4Vfr4DGAJ
        pNMwofXOTQKAfM6T26IQ55aTh8h0f8vTqNdllGOfPxf2jhk7oFEd4y50asiLfs7GroBzhi
        SniVfdiN7b859if3Naq5bA/FhnfbjxvFZ59IVVec7+uIF1BzlWaYrrz1PHyYC5U5l5ouDk
        3W6xaPVLXZ0AAAAcdGFsaGEucmFzaGlkQHRlY2hjcmVhdGl4LmNvbQECAwQFBgc=
        -----END OPENSSH PRIVATE KEY-----' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 165.232.100.44 >> ~/.ssh/known_hosts
        # ssh-keyscan -H 46.101.18.136 >> ~/.ssh/known_hosts

    - name: Validate SSH connection
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no master_mhdgpqenem@165.232.100.44 "echo 'SSH Connection Successful'"

    # - name: Sync files to staging (for test-workflow-branch branch)
    #   if: github.ref == 'refs/heads/test-workflow-branch'
    #   run: |
    #     rsync -avz --delete-after ./ master_mhdgpqenem@165.232.100.44:/home/master/talha_test_dir/staging_dir
    #     # rsync -avz --delete-after ./ master_successfulapps@46.101.18.136:/home/master/applications/cefqxhbhaj/public_html/
